FROM ubuntu:latest

# Evitar prompts interactivos durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update && apt-get install -y \
    python3.10 \
    python3.10-distutils \
    python3.10-dev \
    pipx \
    vim \
    make \
    && rm -rf /var/lib/apt/lists/*

# Instalar pip específicamente para Python 3.10
#RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

# Instalar poetry
#RUN pipx ensurepath \
#    && echo 'eval "$(register-python-argcomplete pipx)"' >> ~/.bashrc \
#    && source ~/.bashrc \
#    && pipx install poetry

RUN curl -fsSL https://opencode.ai/install | bash

WORKDIR /workspace

CMD ["/root/.opencode/bin/opencode","web","--port","4096","--hostname","0.0.0.0"]

